id: IB0A607AA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T02:28:57+00:00'
last_modified: '2022-06-08T10:26:04.260216+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9980
  title: དམིགས་བརྩེ་མའི་ཆོས་སྐོར་སྟོད་སྨད་ཁ་སྐོང་དང་བཅས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DD96:
      image_group_id: I1KG9982
      title: ''
      total_pages: 604
      order: 1
      base_file: DD96.txt
    '9745':
      image_group_id: I1KG9983
      title: ''
      total_pages: 764
      order: 2
      base_file: 9745.txt
    61FF:
      image_group_id: I1KG9984
      title: ''
      total_pages: 660
      order: 3
      base_file: 61FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
